name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache SBT # https://github.com/actions/cache/blob/master/examples.md#scala---sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run compile
        run: sbt 'project ulid4s' +clean +update +compile

      - name: Run tests
        run: sbt 'project ulid4s' coverage test coverageReport

      - name: Aggregate coverage reports
        run: sbt 'project ulid4s' coverageAggregate && sbt 'project ulid4s' coveralls
